'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating product descriptions based on a product name and image.
 *
 * It exports:
 * - `generateProductDescription`: An async function that takes product name and image data URI as input and returns a generated product description.
 * - `GenerateProductDescriptionInput`: The input type for the `generateProductDescription` function.
 * - `GenerateProductDescriptionOutput`: The output type for the `generateProductDescription` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productImage: z
    .string()
    .describe(
      'A photo of the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'  
    ),
  additionalInfo: z.string().optional().describe('Additional information about the product.'),
});
export type GenerateProductDescriptionInput = z.infer<
  typeof GenerateProductDescriptionInputSchema
>;

const GenerateProductDescriptionOutputSchema = z.object({
  description: z
    .string()
    .describe('A compelling product description generated by the AI.'),
});
export type GenerateProductDescriptionOutput = z.infer<
  typeof GenerateProductDescriptionOutputSchema
>;

export async function generateProductDescription(
  input: GenerateProductDescriptionInput
): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}

const generateProductDescriptionPrompt = ai.definePrompt({
  name: 'generateProductDescriptionPrompt',
  input: {schema: GenerateProductDescriptionInputSchema},
  output: {schema: GenerateProductDescriptionOutputSchema},
  prompt: `You are an expert copywriter specializing in product descriptions.

  Based on the product name and image, create a compelling and informative product description.

  Product Name: {{{productName}}}
  Product Image: {{media url=productImage}}
  {{#if additionalInfo}}
  Additional Information: {{{additionalInfo}}}
  {{/if}}

  Description:`, //Crucially important to add "Description:" to the end so that the LLM knows to begin generating the description
});

const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await generateProductDescriptionPrompt(input);
    return output!;
  }
);
