
// DO NOT EDIT, this file is generated by Firebase Studio
'use server';
import { initializeApp, getApps, getApp, App } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import type { ContactMessage } from '@/lib/types';

// Note: This file is now using the Firebase Admin SDK as it's a server-side file.
// Client-side Firebase logic is handled in src/firebase/index.ts

let app: App;
if (!getApps().length) {
  // This is the correct way for hosted environments like Vercel or App Hosting
  // to automatically discover credentials.
  app = initializeApp();
} else {
  app = getApp();
}

const db = getFirestore(app);

const CONTACTS_COLLECTION = 'contacts';

export async function saveContactMessage(message: ContactMessage): Promise<void> {
    await db.collection(CONTACTS_COLLECTION).add({
      ...message,
      createdAt: FieldValue.serverTimestamp(),
    });
}
