

import TopAdBanner from '@/components/top-ad-banner';
import BottomAdBanner from '@/components/bottom-ad-banner';
import Footer from '@/components/footer';
import { Logo } from '@/components/icons';
import { Button } from '@/components/ui/button';
import { Home } from 'lucide-react';
import Link from 'next/link';

export default function TermsOfUsePage() {
  return (
    <div className="flex min-h-screen w-full flex-col">
      <header className="sticky top-0 z-10 flex h-16 items-center justify-between gap-4 border-b bg-background/95 px-4 backdrop-blur md:px-6">
        <nav className="flex items-center gap-2 text-lg font-medium md:text-sm">
          <Link
            href="/"
            className="flex items-center gap-2 font-semibold text-foreground"
          >
            <Logo className="h-6 w-6 text-primary" />
            <span className="font-semibold">Leo Creator</span>
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Button variant="outline" asChild>
            <Link href="/">
              <Home className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>
        </div>
      </header>
      <main className="flex-1 p-4 md:p-8 lg:p-10">
        <div className="mx-auto max-w-4xl prose dark:prose-invert">
            <h1>Terms of Use</h1>
            <TopAdBanner />
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

            <p>Please read these Terms of Use ("Terms", "Terms of Use") carefully before using the Leo Creator website (the "Service") operated by Leo Creator ("us", "we", or "our").</p>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.</p>

            <h2>2. Use of Services</h2>
            <p>You agree to use our services for lawful purposes only. You are prohibited from using the services to:</p>
            <ul>
                <li>Generate content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
                <li>Impersonate any person or entity.</li>
                <li>Upload or transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware.</li>
            </ul>

            <h2>3. Intellectual Property</h2>
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Leo Creator and its licensors. You may use the content generated by the tools for your own purposes, but you may not resell the service itself.</p>
            
            <h2>4. Disclaimers</h2>
            <p>The services are provided "as is." We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>

            <h2>5. Limitation of Liability</h2>
            <p>In no event shall Leo Creator, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
            
            <h2>6. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the company is based, without regard to its conflict of law provisions.</p>
            
            <h2>7. Changes</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.</p>

            <h2>8. Contact Us</h2>
            <p>If you have any questions about these Terms, please <Link href="/contact">contact us</Link>.</p>
        </div>
      </main>
      <BottomAdBanner />
      <Footer />
    </div>
  );
}
